### ISSUE TITLE
Duplicate wrapRootElement

### ISSUE THREAD

**Issue by BrunoBoehm** [jlengstorf/gatsby-with-apollo#1]
Hey there, thanks for this useful example!
Is there a reasons one should duplicate the wrapRootElement in both Browser and SRR js files or was it just to show both were possible?
I haven't found in the docs the difference between browser.js and srr.js could you point me to the right resource?
Thanks a lot!

**Comment by bryndyment** [comment]
Not attempting to answer your question, but here's a link to the relevant Gatsby doc:

https://www.gatsbyjs.org/docs/gatsby-project-structure/#files

Also, here's a link to the associated presentation:

https://www.youtube.com/watch?v=wNUg1jpj9T0

**Comment by jlengstorf** [comment]
Hi! (I just realized I had unwatched this repo and missed a bunch of issues. 😱) This need to be duplicated because `gatsby-browser.js` is used on the client side (e.g. when the site is run in the browser) and `gatsby-ssr.js` is used during the build process. In this case they’re identical (I made an effort to DRY this out in #6) but that’s not always the case, which is why these are separate files.
