### ISSUE TITLE
Does this work with latest Gatsby? 

### ISSUE THREAD

**Issue by cif** [jlengstorf/gatsby-with-apollo#8]
Gatsby@2.19.12 complains about any queries I have wrapped in `graphql-tag` for runtime Apollo queries at build time. e.g.

```
GraphQLDocumentError: Cannot query field "getCustomer" on type "Query".
        at /Users/benipsen/Development/moonshot-client/src/providers/AuthProvider.tsx:2:3
```

Any way to prevent Gatsby from doing this and just let alone the runtime queries? 

Love the static builds Gatsby does, but this is for login / customer data.

**Comment by cif** [comment]
Follow up, I can get around this by making my own __tag module i.g. `import gql from '__tag`.  This would indicate to me that a gatsby is possibly (likely?) stomping on the `graphql-tag` module using the require cache at build time.  This is an unfortunate flexibility in node, which I myself have abused... Will consider opening an issue in Gastby repo vs here

**Comment by cif** [comment]
Here's my workaround for now https://www.npmjs.com/package/not-graphql-tag

**Comment by jlengstorf** [comment]
hmmm — yeah, that definitely sounds like something upstream in Gatsby

I'm going to close this because there's no way for this demo to address that issue, but if you don't mind referencing this issue in the Gatsby issue so future Googlers can follow the thread, I'd very much appreciate that

thank you!
